### ISSUE TITLE
dump1090.c:46:21: fatal error: 'rtl-sdr.h' file not found

### ISSUE THREAD

**Issue by kruug** [antirez/dump1090#108]
Hi.

Whilst in the dump1090 directory I run the "make" command in Terminal ( Debian Testing "stretch" ) which results in the following error:

`dump1090.c:46:21: fatal error: 'rtl-sdr.h' file not found`

Running `sudo apt-get install rtl-sdr` returns `rtl-sdr is already the newest version (0.5.3-11).`

Any suggestions?

Thanks

**Comment by 0xFACE** [comment]
You probably need librtlsdr-dev package.

**Comment by kruug** [comment]
That did the trick!  Thanks!
