### ISSUE TITLE
Error while Compling make

### ISSUE THREAD

**Issue by PRRvalli** [antirez/dump1090#114]
When I'm trying to execute the make file I get error like this. Can some one help me 
`Package librtlsdr was not found in the pkg-config search path.
Perhaps you should add the directory containing `librtlsdr.pc'
to the PKG_CONFIG_PATH environment variable
No package 'librtlsdr' found
cc -g -o dump1090 dump1090.o anet.o   -lpthread -lm
dump1090.o: In function `modesInitRTLSDR':
/home/prr/my_project/dump1090-master/dump1090.c:340: undefined reference to `rtlsdr_get_device_count'
/home/prr/my_project/dump1090-master/dump1090.c:348: undefined reference to `rtlsdr_get_device_usb_strings'
/home/prr/my_project/dump1090-master/dump1090.c:353: undefined reference to `rtlsdr_open'
/home/prr/my_project/dump1090-master/dump1090.c:360: undefined reference to `rtlsdr_set_tuner_gain_mode'
/home/prr/my_project/dump1090-master/dump1090.c:372: undefined reference to `rtlsdr_set_tuner_gain'
/home/prr/my_project/dump1090-master/dump1090.c:377: undefined reference to `rtlsdr_set_freq_correction'
/home/prr/my_project/dump1090-master/dump1090.c:378: undefined reference to `rtlsdr_set_agc_mode'
/home/prr/my_project/dump1090-master/dump1090.c:379: undefined reference to `rtlsdr_set_center_freq'
/home/prr/my_project/dump1090-master/dump1090.c:380: undefined reference to `rtlsdr_set_sample_rate'
/home/prr/my_project/dump1090-master/dump1090.c:381: undefined reference to `rtlsdr_reset_buffer'
/home/prr/my_project/dump1090-master/dump1090.c:383: undefined reference to `rtlsdr_get_tuner_gain'
/home/prr/my_project/dump1090-master/dump1090.c:368: undefined reference to `rtlsdr_get_tuner_gains'
dump1090.o: In function `readerThreadEntryPoint':
/home/prr/my_project/dump1090-master/dump1090.c:460: undefined reference to `rtlsdr_read_async'
dump1090.o: In function `main':
/home/prr/my_project/dump1090-master/dump1090.c:2632: undefined reference to `rtlsdr_close'
collect2: error: ld returned 1 exit status
make: *** [dump1090] Error 1
`

**Comment by yuvadm** [comment]
Install librtlsdr system wide and try again
