### ISSUE TITLE
No supported RTLSDR devices found.

### ISSUE THREAD

**Issue by wdx7266** [antirez/dump1090#115]
When I reviewed the issues, I found  [No device found #89](https://github.com/antirez/dump1090/issues/89)

However, When I try:

> hackrf_whatever -f 1090000000 | dump1090 --ifile -

It just tell me:

> hackrf_whatever -f 1090000000 | dump1090 --ifile -
> Fri Apr  7 16:59:57 2017 CST  dump1090-mutability v1.15-dev-326-g0034962 starting up.
> Using sample converter: UC8, integer/table path
> hackrf_whatever: command not found
> Fri Apr  7 16:59:57 2017 CST  Waiting for receive thread termination
> Fri Apr  7 16:59:57 2017 CST  Normal exit.

so, what should I do to fix:

> hackrf_whatever: command not found

**Comment by yuvadm** [comment]
Your `hackrf_whatever` executable isn't found, this has nothing to do with dump1090. Plus, you're using the Mutability fork, so please open any issues at https://github.com/mutability/dump1090/
