### ISSUE TITLE
No traffic info

### ISSUE THREAD

**Issue by usagi87** [antirez/dump1090#123]
dump1090 starts fine. But doesnt print any information, and if does on shows one plane. when using rtl_adsb receives  ads-b info show there is traffic plus I live close to a airport.

**Comment by betaversionsoftware** [comment]
There could be a lot of reasons, what is the command line that you are using to start up dump1090?

**Comment by usagi87** [comment]
./dump1090 
./dump1090 --interactive

**Comment by yuvadm** [comment]
Is there any reason to suspect this is a software issue? Please debug your hardware setup and reopen only once you have evidence of a bug.
