### ISSUE TITLE
Please consider making a release

### ISSUE THREAD

**Issue by highvoltage** [antirez/dump1090#130]
Hi!

Thanks for this software, I'm intending to package this for Debian.

Would you consider tagging a release for this? Would make it easier to track instead of just following git.

**Comment by BenjiWiebe** [comment]
@highvoltage Not sure if you are aware of this, but there are at least two other forks of this software with more features and/or more recent updates: https://github.com/mutability/dump1090, and https://github.com/MalcolmRobb/dump1090.

**Comment by highvoltage** [comment]
Thanks @BenjiWiebe - I learned about those shortly after posting that, closing issue.
