### ISSUE TITLE
Provide required libraries in Readme

### ISSUE THREAD

**Issue by joekerna** [antirez/dump1090#131]
Please provide a list of requirements for compiling in the Readme.
For example I had to google for quite a while to find out I needed  `librtlsdr-dev `

**Comment by yuvadm** [comment]
`librtlsdr` is the only library required as can be verified in the [Makefile](https://github.com/antirez/dump1090/blob/master/Makefile), it's also a pretty obvious dependency given this is an RTLSDR-based project. Feel free to provide a PR if you think the README can be improved, otherwise closing.
