### ISSUE TITLE
Web interface needs an update

### ISSUE THREAD

**Issue by felixtremblay** [antirez/dump1090#136]
Google maps seems to have changed some things with its api. When I load the page, I am greeted with a popup saying : "this page can't load google maps correctly". After dismissing the alert, the map shown is really dark and has a bunch of "for development only" watermarks.

**Comment by jay-to-the-dee** [comment]
Can confirm this issue. Unfortunately solution @HarryMJensen didn't work for me :(

**Comment by jay-to-the-dee** [comment]
It appears their needs to be an API key for this to work now. Worth mentioning how to do this in the README doc?

**Comment by HNJAMeindersma** [comment]
About a year ago Google did some things to their  Maps API. Other branches of dump1090 and I believe even this one has moves to the OpenStreetMaps API since then.

**Comment by danstreeter** [comment]
As above, I've requested a PR that fixes this issue - I've done it in a forked repo which my codebase derives from which is also further ahead of this one: although the changes made are very small and are easily transferable as required.

**Comment by PHPoenX** [comment]
> OpenStreetMaps

It is wrong shows a lot of locations

**Comment by antirez** [comment]
Hi, I ported the code to open street map. Closing.
