### ISSUE TITLE
Error occurs while compilation

### ISSUE THREAD

**Issue by freethinker-coder** [antirez/dump1090#167]
![error](https://user-images.githubusercontent.com/104486175/165454836-685ebe80-54fb-4673-9dfc-a16142a7b733.png)
An error occurs
![error](https://user-images.githubusercontent.com/104486175/165454971-c17783e1-4976-48bf-a9c4-7abc3689aa12.png)

rtl-sdr-fm.cpp:40:10: fatal error: rtl-sdr.h: No such file or directory
   40 | #include <rtl-sdr.h>

**Comment by irly01** [comment]
me too

**Comment by alexmyczko** [comment]
was os/release? do you have rtl-sdr.h? (locate rtl-sdr.h or find /usr/ -name rtl-sdr.h)

**Comment by fcatt** [comment]
Install the package **librtlsdr-dev** (Debian/Ubuntu) or **rtl-sdr-devel** (Redhat/Fedora)
