### ISSUE TITLE
Error when opening dump1090

### ISSUE THREAD

**Issue by itayfish** [antirez/dump1090#173]
Found 2 device(s):
**0: É■↓, ñ■↓, SN:  (currently selected)
1: Realtek, RTL2838UHIDIR, SN: 00000001
usb_open error -12
Error opening the RTLSDR device: No error**

C:\Users\itayf\Desktop\dump1090>pause
Press any key to continue . . .

How do I solve this error? also how do I select the RTL device and not the 1st one?

**Comment by lou12331** [comment]
try to add --device-index 1
