### ISSUE TITLE
Crashes with message "cb transfer status: 1, canceling..."

### ISSUE THREAD

**Issue by e2jk** [antirez/dump1090#33]
I've been running dump1090 for a few days on a Raspberry Pi, first down in my garden (not a super reception ~50km, but good enough to start testing). Now that I've moved it up on the roof (same hardware/antenna), I'm getting a lot of crashes with the message "cb transfer status: 1, canceling..." (I've also seen a few time the number 5, but much less).

I run dump 1090 from source (retrieved ~ a week ago, i.e. acecc6d79b8828ee14c213144311a0fb9aff3d8e) from it's own folder by running
$ ./dump1090 --interactive --net

It looks like if I don't request the web page, it will stay a bit longer (2-3 hours?), but will eventually crash. If I request the web page directly, the crash can happen in a few minutes.

I have a suspicion it might be due to more signals being retrieved from my roof, and maybe my Raspberry Pi then struggles to decode it all? The weird part is that `top` doesn't return horrible values (~30% CPU and 2% memory usage):

  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND  
 2676 pi        20   0 14808 4664  828 R  30.2  2.0   0:10.70 dump1090  

EDIT: Info about my hardware:
Raspberry Pi Model B first generation (256mb RAM) running Raspbian with self-compiled Linux kernel 3.8.13+ (to have driver support directly from the Kernel for my DVB stick)
Connected using a wireless stick, computer is 2 stairs above the router, not great wifi reception.
Terratec Cinergy TStick RC (rev 3), contains E4000 tuner and RealTek RTL2832U. When starting Dump1090 this is displayed:
Found 1 device(s):
0: Realtek, RTL2838UHIDIR, SN: 00000001 (currently selected)
Found Elonics E4000 tuner

I'm currently using the antenna supplied with the DVB stick, I've made a dipole as shown on your blog but am not seeing major differences (probably some implementation fault on my side ;) )

I'm also pushing my data back up to FlightRadar24 using their precompiled binary for ARM, dynamically linked. Not sure if that could have an impact?

Would you have any idea what status 1 or 5 for "cb transfer" points to?

**Comment by vranki** [comment]
Would it be possible to detect the situation and give more verbose error description? 

"Detected flaky connection to USB dongle - please try different port or a powered USB HUB"

**Comment by Crogge** [comment]
It can happen randomly with some dongles or other USB devices causing short USB controller resets, I think it would be useful any option to do an auto restart. Right now I have a simple bash script which does it if a certain amount of these msgs appear in the logfile.
