### ISSUE TITLE
Minor change for my own convenience

### ISSUE THREAD

**Issue by WealdenSmith** [antirez/dump1090#57]
Hi, So that I don't have to go rummaging around in the main code, I've changed one line and added one line in gmap.html.

The standard initial zoom of 5 was far too small for me. I needed a zoom of 11 initially as I live under a flight path into & out of LGW.

After line 42 I added:

InitZoom=11;

and at line 156 I changed the code to:

zoom: InitZoom,

Now the CenterLat, CenterLon and InitZoom initialisations are conveniently near the start of the code.

I also changed CenterLat/Lon to my house so the browser starts up showing traffic in my immediate vicinity.

Great bit of software. Many thanks.

Chris

**Comment by yuvadm** [comment]
These changes are user-specific and will not be merged into this repo. Also, in the future, you should open a proper [pull request](https://help.github.com/articles/using-pull-requests/) so maintainers can actually look at a patch.
