### ISSUE TITLE
Have some ideas, may fork

### ISSUE THREAD

**Issue by Pokey1** [antirez/dump1090#59]
I just started using D1090 and I have a bunch of ideas I want to implement.  I was thinking about forking the Malcolm Robb fork but I just looked and there are a lot of forks out there already.  Not sure if I should start another one.  Below are my ideas and a mockup.  

1. When a new aircraft is first mapped, a sound will be played.
2. Mapped aircraft will have an info window that displays flight, equipment, fare, plan, altitude.
3. The right frame will be converted to an accordion and default to closed.
4. Aircraft that do not transmit lat/long will be appear as UFOs and include a signal level meter.
5. SQL Lite will be installed and track all mapped aircraft.  
6. Data points to save will be ICAO, flight, equipment, date last seen, on-time rating.
7. There will be a settings menu to set these options.
8. Aircraft markers will default to always have tail lines.
9. If an aircraft is above a set altitude, two tail lines representing contrails will appear.
10. The contrails will become a single line once an aircraft is below a set altitude.
11. The contrails should merge together/apart as the aircraft gains/loses altitude.
12. Once an aircraft lands, the color of the icon should change to green.
13. The marker icon should change based on the type of equipment.
14. A centralized DB will be created to manage N Number mapping.
15. If an aircraft is screaming overhead, the flight and altitude will be announced.  
16. Mac OS and/or Festival will be used for speech.
17. The on-time rating will be defined as: 90% ontime = A, 80% B, 70% C, 60% D, below F.
18. Colors of the lines will change based on altitude.  
19. If some info is not available, e.g. equipment, it will not be shown on the info window.
20. The marker should scale in size when you zoom.

![1090 example](https://cloud.githubusercontent.com/assets/8534132/4022264/79e6d1dc-2b26-11e4-9a2d-520f0af30081.png)

**Comment by yuvadm** [comment]
These are all very nice ideas. Feel free to implement them on your own fork, and open a pull request. Until then, closing this issue.
