### ISSUE TITLE
BaseStation format

### ISSUE THREAD

**Issue by jestemradek** [antirez/dump1090#6]
Hello,

very popular format of data is BaseStation, eg. FR24 app use this format of data, but dump1090 have only AVR :(

Is there a chance to support BS format by dump1090?

There is source of similar funcionality:
http://diseqc.org.ua/projects/hard/adsb/adsbox-20120427.tar.gz

Best Regards
Radek

**Comment by yuvadm** [comment]
Fixed in 071a021f2046a6ca6c06d8869c4d47c9f474a8dd
