### ISSUE TITLE
Anirez vs Marco Robb 

### ISSUE THREAD

**Issue by Marsfan** [antirez/dump1090#69]
I know that this is the origional version of dump1090, but the github user malcomrobb seems to have made many more commits. Which is more up to date and feature laden, and which would I fork?

**Comment by yuvadm** [comment]
Which ever version suits your needs. This is the original, more lightweight repo, whlie MalcolmRobb's fork has much more added features.

**Comment by Marsfan** [comment]
What extra features?

**Comment by Marsfan** [comment]
What extra features?
