### ISSUE TITLE
Raw-data Client

### ISSUE THREAD

**Issue by b2jossi** [antirez/dump1090#7]
Hi,

actually ADSB# includes an Hub which allows to build your own network like FR24. To use this hub it is necessary to activley connect your client to this hub. At the moment I do this using dump1090 and socat to forward the data from your pretty good software to the hub. It would realy be a nice feature if there would be the possibility to do this within dump1090. You "just" need to establish a connection to a given host and port and send the raw data to it. Of course some kind of automatic reconnection after a drop (maybe due to some DSL reconnect) would be nice ;)

Maybe you can think about ;)

Best regards,
Johannes

**Comment by yuvadm** [comment]
This seems to be out of scope for dump1090, closing.
