### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by belisards** [antirez/dump1090#89]
rad1o (hackRF) does not work (without sudo too) with dump1090, any ideia why?

abitporu@hpnote:~/rad1o/dump1090$ sudo hackrf_info 
Found HackRF board.
Board ID Number: 3 (Unknown Board ID)
Firmware Version: git-dfbbbfb
Part ID Number: 0xa0000a30 0x00624747
Serial Number: 0x00000000 0x00000000 0xa83065d9 0x213f5127
abitporu@hpnote:~/rad1o/dump1090$ sudo ./dump1090 
No supported RTLSDR devices found.

**Comment by yuvadm** [comment]
HackRF isn't an RTLSDR device.

**Comment by belisards** [comment]
ooops, sorry for this dumb question, but is there a way to run dump1090 with hackrf?

**Comment by yuvadm** [comment]
Use any hackrf program you have to pipe the data to stdin:

    hackrf_whatever -f 1090000000 | dump1090 --ifile -
