### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by ifan-boy** [antirez/dump1090#95]
i got these error when i try to type 'make'. i have already install gnuradio.

make: pkg-config: Command not found
cc -g -o dump1090 dump1090.o anet.o   -lpthread -lm
dump1090.o: In function `modesInitRTLSDR':
/home/user/Downloads/software/dump1090/dump1090.c:340: undefined reference to `rtlsdr_get_device_count'
/home/user/Downloads/software/dump1090/dump1090.c:348: undefined reference to `rtlsdr_get_device_usb_strings'
/home/user/Downloads/software/dump1090/dump1090.c:353: undefined reference to `rtlsdr_open'
/home/user/Downloads/software/dump1090/dump1090.c:360: undefined reference to `rtlsdr_set_tuner_gain_mode'
/home/user/Downloads/software/dump1090/dump1090.c:372: undefined reference to `rtlsdr_set_tuner_gain'
/home/user/Downloads/software/dump1090/dump1090.c:377: undefined reference to `rtlsdr_set_freq_correction'
/home/user/Downloads/software/dump1090/dump1090.c:378: undefined reference to `rtlsdr_set_agc_mode'
/home/user/Downloads/software/dump1090/dump1090.c:379: undefined reference to `rtlsdr_set_center_freq'
/home/user/Downloads/software/dump1090/dump1090.c:380: undefined reference to `rtlsdr_set_sample_rate'
/home/user/Downloads/software/dump1090/dump1090.c:381: undefined reference to `rtlsdr_reset_buffer'
/home/user/Downloads/software/dump1090/dump1090.c:383: undefined reference to `rtlsdr_get_tuner_gain'
/home/user/Downloads/software/dump1090/dump1090.c:368: undefined reference to `rtlsdr_get_tuner_gains'
dump1090.o: In function `readerThreadEntryPoint':
/home/user/Downloads/software/dump1090/dump1090.c:460: undefined reference to `rtlsdr_read_async'
dump1090.o: In function `main':
/home/user/Downloads/software/dump1090/dump1090.c:2632: undefined reference to `rtlsdr_close'
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'dump1090' failed
make: *** [dump1090] Error 1

**Comment by yuvadm** [comment]
> make: pkg-config: Command not found

You do not have pkg-config installed on your system
