### ISSUE TITLE
dump1090.c:46:10: fatal error: 'rtl-sdr.h' file not found

### ISSUE THREAD

**Issue by barrygee** [antirez/dump1090#98]
Hi.

Whilst in the dump1090 directory I run the "make" command in Terminal ( OS X ) which results in the following error:

`dump1090.c:46:10: fatal error: 'rtl-sdr.h' file not found`

Any suggestions? 

Thanks

**Comment by yuvadm** [comment]
Install rtl-sdr on your system then you'll be able to compile dump1090.
